# Generated by Django 4.2.9 on 2026-02-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("tagline", models.CharField(blank=True, default="", max_length=500)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("favicon_url", models.URLField(blank=True, default="")),
                (
                    "colour_primary",
                    models.CharField(default="hsl(220, 70%, 50%)", max_length=50),
                ),
                (
                    "colour_secondary",
                    models.CharField(default="hsl(220, 70%, 30%)", max_length=50),
                ),
                (
                    "colour_accent",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "colour_background",
                    models.CharField(default="#ffffff", max_length=50),
                ),
                ("colour_text", models.CharField(default="#333333", max_length=50)),
                ("font_heading", models.CharField(default="system-ui", max_length=100)),
                ("font_body", models.CharField(default="system-ui", max_length=100)),
                ("font_url", models.URLField(blank=True, default="")),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("address", models.TextField(blank=True, default="")),
                ("website_url", models.URLField(blank=True, default="")),
                ("social_facebook", models.URLField(blank=True, default="")),
                ("social_instagram", models.URLField(blank=True, default="")),
                ("social_twitter", models.URLField(blank=True, default="")),
                ("business_hours", models.JSONField(blank=True, default=dict)),
                ("booking_lead_time_hours", models.IntegerField(default=24)),
                ("booking_max_advance_days", models.IntegerField(default=60)),
                ("cancellation_policy", models.TextField(blank=True, default="")),
                ("deposit_percentage", models.IntegerField(default=0)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                ("currency_symbol", models.CharField(default="£", max_length=5)),
                (
                    "pwa_theme_colour",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "pwa_background_colour",
                    models.CharField(default="#ffffff", max_length=50),
                ),
                (
                    "pwa_short_name",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant Settings",
                "verbose_name_plural": "Tenant Settings",
                "db_table": "tenants_settings",
            },
        ),
    ]
