# Generated by Django 4.2.9 on 2026-02-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="enabled_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of enabled module names e.g. ["bookings","payments","staff"]',
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="slug",
            field=models.SlugField(
                default="default",
                help_text="URL-safe identifier e.g. salon-x",
                max_length=100,
                unique=True,
            ),
        ),
    ]
