# Generated by Django 4.2.9 on 2026-02-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("price_pence", models.PositiveIntegerField(default=0)),
                ("deposit_pence", models.PositiveIntegerField(default=0)),
                ("colour", models.CharField(blank=True, default="", max_length=50)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bookings_service",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("max_bookings", models.PositiveIntegerField(default=1)),
                ("is_available", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="bookings.service",
                    ),
                ),
            ],
            options={
                "db_table": "bookings_timeslot",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("price_pence", models.PositiveIntegerField(default=0)),
                ("deposit_pence", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                (
                    "payment_session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="bookings.service",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="bookings.timeslot",
                    ),
                ),
            ],
            options={
                "db_table": "bookings_booking",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["date", "start_time", "is_available"],
                name="bookings_ti_date_6f1066_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "created_at"], name="bookings_bo_status_72dd85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer_email"], name="bookings_bo_custome_f6e328_idx"
            ),
        ),
    ]
