# Generated by Django 5.2.11 on 2026-02-06 09:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_staff_photo_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "class_count",
                    models.IntegerField(
                        help_text="Number of classes included in this package",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "validity_days",
                    models.IntegerField(
                        default=365,
                        help_text="Number of days until package expires after purchase",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Class Package",
                "verbose_name_plural": "Class Packages",
                "ordering": ["class_count"],
            },
        ),
        migrations.CreateModel(
            name="IntakeWellbeingDisclaimer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20, unique=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Disclaimer text shown to users during intake"
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Wellbeing Disclaimer",
                "verbose_name_plural": "Wellbeing Disclaimers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount paid for this booking",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_id",
            field=models.CharField(
                blank=True,
                help_text="Payment reference ID from payment system",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Payment Pending"),
                    ("paid", "Paid"),
                    ("failed", "Payment Failed"),
                    ("refunded", "Refunded"),
                    ("credit_used", "Credit Used"),
                ],
                default="pending",
                help_text="Payment status from payment system",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("single_class", "Single Class"),
                    ("package", "Class Package"),
                    ("credit", "Used Credit"),
                ],
                default="single_class",
                help_text="Type of payment used",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="staff_members", to="bookings.service"
            ),
        ),
        migrations.CreateModel(
            name="ClientCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_classes",
                    models.IntegerField(
                        help_text="Total classes in this credit package",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "remaining_classes",
                    models.IntegerField(
                        help_text="Classes remaining to be used",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment system reference for this purchase",
                        max_length=200,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid for this package",
                        max_digits=10,
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Date when unused credits expire"),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Whether credits can still be used"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="bookings.client",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        help_text="Package that generated these credits",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_credits",
                        to="bookings.classpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Credit",
                "verbose_name_plural": "Client Credits",
                "ordering": ["-purchased_at"],
            },
        ),
        migrations.CreateModel(
            name="IntakeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("emergency_contact_name", models.CharField(max_length=200)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        help_text="e.g., First time, Some experience, Regular practitioner",
                        max_length=50,
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        blank=True,
                        help_text="What would you like to achieve from your sessions? (Optional)",
                    ),
                ),
                (
                    "preferences",
                    models.TextField(
                        blank=True,
                        help_text="Any preferences or notes for your facilitator? (Optional)",
                    ),
                ),
                (
                    "consent_booking",
                    models.BooleanField(
                        default=False,
                        help_text="Consent to book sessions and store booking data",
                    ),
                ),
                (
                    "consent_marketing",
                    models.BooleanField(
                        default=False,
                        help_text="Consent to receive updates and wellness information",
                    ),
                ),
                (
                    "consent_privacy",
                    models.BooleanField(
                        default=False,
                        help_text="Confirmed reading and accepting privacy policy",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Intake form completed and validated"
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when questionnaire was completed",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expiry date (1 year from completion) - must be renewed annually",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intake Profile",
                "verbose_name_plural": "Intake Profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="bookings_in_email_3eae8c_idx"),
                    models.Index(
                        fields=["completed"], name="bookings_in_complet_f3674b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Package Purchase"),
                            ("single", "Single Class Purchase"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_system_id",
                    models.CharField(
                        help_text="Unique ID from payment system (e.g., Stripe payment intent ID)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                (
                    "payment_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional payment data from payment system",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="bookings.client",
                    ),
                ),
                (
                    "credit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Credit record created (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.clientcredit",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        help_text="Package purchased (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.classpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment_system_id"],
                        name="bookings_pa_payment_1f4fec_idx",
                    ),
                    models.Index(
                        fields=["status"], name="bookings_pa_status_111f84_idx"
                    ),
                ],
            },
        ),
    ]
