# Generated by Django 4.2.9 on 2026-02-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0012_demo_data_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="staffschedule",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="staffschedule",
            name="break_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="risk_level",
            field=models.CharField(
                blank=True,
                default="",
                help_text="LOW / MEDIUM / HIGH / CRITICAL",
                max_length=10,
            ),
        ),
    ]
