# Generated by Django 4.2.9 on 2026-02-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0013_alter_staffschedule_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reminder_sent_1h",
            field=models.BooleanField(
                default=False, help_text="1-hour reminder email sent"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="reminder_sent_24h",
            field=models.BooleanField(
                default=False, help_text="24-hour reminder email sent"
            ),
        ),
    ]
