# Generated by Django 4.2.9 on 2026-02-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("REVENUE", "Revenue"),
                            ("EFFICIENCY", "Efficiency"),
                            ("MARKETING", "Marketing"),
                            ("COMPLIANCE", "Compliance"),
                            ("STAFFING", "Staffing"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("is_dismissed", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_recommendation",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
