# Generated by Django 4.2.9 on 2026-02-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_contact_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags e.g. VIP,Lapsed",
                max_length=500,
            ),
        ),
    ]
