# Generated by Django 4.2.9 on 2026-02-08 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(default="", max_length=150)),
                ("user_role", models.CharField(default="", max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("EXPORT", "Export"),
                            ("STATUS_CHANGE", "Status Change"),
                            ("ROLE_CHANGE", "Role Change"),
                            ("PASSWORD_CHANGE", "Password Change"),
                        ],
                        max_length=30,
                    ),
                ),
                ("entity_type", models.CharField(default="", max_length=100)),
                ("entity_id", models.CharField(default="", max_length=100)),
                ("details", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Entry",
                "verbose_name_plural": "Audit Entries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
