# Generated by Django 4.2.9 on 2026-02-08 12:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("provider", models.CharField(default="stripe", max_length=50)),
                (
                    "provider_customer_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payments_customer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payable_type", models.CharField(db_index=True, max_length=100)),
                ("payable_id", models.CharField(db_index=True, max_length=255)),
                ("amount_pence", models.IntegerField()),
                ("currency", models.CharField(default="GBP", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(default="stripe", max_length=50)),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("success_url", models.TextField()),
                ("cancel_url", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("processed_events", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_sessions",
                        to="payments.customer",
                    ),
                ),
            ],
            options={
                "db_table": "payments_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gross_amount_pence", models.IntegerField()),
                ("fee_amount_pence", models.IntegerField(blank=True, null=True)),
                ("net_amount_pence", models.IntegerField(blank=True, null=True)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                (
                    "captured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "provider_charge_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.paymentsession",
                    ),
                ),
            ],
            options={
                "db_table": "payments_transaction",
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_pence", models.IntegerField()),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "provider_refund_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "payments_refund",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentsession",
            index=models.Index(
                fields=["payable_type", "payable_id"],
                name="payments_se_payable_04c0a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentsession",
            index=models.Index(
                fields=["status", "created_at"], name="payments_se_status_998d20_idx"
            ),
        ),
    ]
