# Generated by Django 4.2.9 on 2026-02-08 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "documents_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("POLICY", "Policy"),
                            ("PROCEDURE", "Procedure"),
                            ("FORM", "Form"),
                            ("CERTIFICATE", "Certificate"),
                            ("CONTRACT", "Contract"),
                            ("TRAINING", "Training"),
                            ("HSE", "HSE"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("file_size", models.CharField(blank=True, default="", max_length=50)),
                (
                    "tier_access",
                    models.CharField(
                        choices=[
                            ("customer", "Customer+"),
                            ("staff", "Staff+"),
                            ("manager", "Manager+"),
                            ("owner", "Owner Only"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="documents.documenttag"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents_document",
                "ordering": ["-created_at"],
            },
        ),
    ]
