# Generated by Django 4.2.9 on 2026-02-13 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0013_alter_staffschedule_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("compliance", "0002_enhance_compliance_add_accidents"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "colour",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional CSS colour",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LEGAL", "Legal Requirement"),
                            ("POLICY", "Policy"),
                            ("INSURANCE", "Insurance"),
                            ("COMPLIANCE", "Compliance"),
                            ("TRAINING", "Training Certificate"),
                            ("HEALTH_SAFETY", "Health & Safety"),
                            ("HR", "HR"),
                            ("CONTRACT", "Contract"),
                            ("GENERAL", "General"),
                        ],
                        db_index=True,
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/%Y/%m/"
                    ),
                ),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "reminder_days_before",
                    models.PositiveIntegerField(
                        default=30, help_text="Days before expiry to trigger reminder"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("owner", "Owner Only"),
                            ("manager", "Manager+"),
                            ("staff", "All Staff"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                (
                    "is_placeholder",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this is a required-document placeholder (no file uploaded yet)",
                    ),
                ),
                (
                    "regulatory_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Legal/regulatory reference e.g. Health and Safety at Work Act 1974",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compliance_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a compliance register item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vault_documents",
                        to="compliance.complianceitem",
                    ),
                ),
                (
                    "linked_staff",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to a staff member (for training certs)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vault_documents",
                        to="bookings.staff",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="documents.documenttag"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vault_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "-created_at"],
            },
        ),
    ]
