# Generated by Django 4.2.9 on 2026-02-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="vault/%Y/%m/"),
        ),
    ]
